name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-npm:
    name: Test NPM
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      # Setup Node and NPM
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build and test
      - name: Build and Test
        working-directory: npm
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test

  test-bash:
    name: Test Bash
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      # Setup BATS
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      # Build and test
      - name: Build and Test
        working-directory: bash
        run: |
          chmod +x ./fail-whale.bash
          bats ./tests/fail-whale.bats

  test-dotnet:
    name: Test Dotnet
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Build and Test
        working-directory: dotnet
        run: |
          dotnet test ./FailWhale.sln
