name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test-npm:
    name: Test NPM
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      # Setup Node and NPM
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Build and test
      - name: Build and Test
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn test
          