name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      # Setup Node and NPM
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      # Build and test
      - name: Build and Test
        working-directory: npm
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Publish
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish --access public . || echo 'Version already exists'

  publish-dontnet:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Publish
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ./dotnet/FailWhale/FailWhale.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{ secrets.NUGET_TOKEN }}

  publish-rust:
    name: Publish Rust Crate
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Publish Crate
        uses: StephenMP/publish-crates@v1.1.0
        with:
          path: "./rust"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          pass-on-no-unpublished-changes: true
